/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal installs and kept here so the
// manually scaffolded project type-checks cleanly after dependencies install.
